import React, { useState, useEffect } from "react";
import DefaultLayout from "../../layouts/DefaultLayout";
import Card from "../../components/Card/Card";
import Head from "next/head";

const Cat = () => {
  const [cats, setCats] = useState([]);
  const fetchCats = async () => {
    const response = await fetch("/api/cats");
    const data = await response.json();
    setCats(data);
  };
  useEffect(() => {
    fetchCats();
  }, []);
  return (
    <>
      <Head>
        <title> Cat catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <DefaultLayout>
        <div className="container">
          <div className="row gx-5 mt-5">
            {cats.map((cat) => (
              <div
                className="col-lg-3 col-md-4 col-cm-6 col-xs-12 p-3"
                key={cat.id}
              >
                <Card cat={cat} />
              </div>
            ))}
          </div>
        </div>
      </DefaultLayout>
    </>
  );
};

export default Cat;
