import Head from "next/head";
import Image from "next/image";
import Jumbotron from "../components/Jumotron/Jumbotron";
import DefaultLayout from "../layouts/DefaultLayout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome at shelter</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/logo.ico" />
      </Head>
      <DefaultLayout>
        <Jumbotron />
      </DefaultLayout>
    </div>
  );
}
